import "./globals.css";
import { Inter } from "next/font/google";
import { CounterProvider } from './context/CounterProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className="flex justify-center items-center h-screen">
          <CounterProvider>{children}</CounterProvider>
          <div>{team}</div>
          <div>{analytics}</div>
        </div>
      </body>
    </html>
  );
}
