import "./globals.css";
import { Inter } from "next/font/google";
import { Dancing_Script } from "next/font/google";
import { CounterProvider } from "./context/CounterProvider";

const inter = Inter({ subsets: ["latin"] }); //
const dancingScript = Dancing_Script({ subsets: ["latin"] }); //

export const metadata = {
  title: {
    default: "Create Next App",
    template: `%s | Next App`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  team,
  analytics,
}: {
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={dancingScript.className}>
        <div className="flex justify-center items-center h-screen">
          <CounterProvider>{children}</CounterProvider>
        </div>
      </body>
    </html>
  );
}
